module.exports = {
  src: require("~/assets/portfolio/aiongemu.jpg"),
  title: "Aion Galaxy Emu",
  subtitle: "Aion game server emulation project",
  desc: "Aion game server emulation project based on aionxemu.",
  role: "Organised a team of 5 developers from 4 countries to rework an outdated game server engine for Aion, written 90% in Java. Reverse engineered and emulated the original copy of NCSoft's Aion. Created entire open-source community on a platform based on iPboard fully supported by donations.",
  status: "ended",
  stage: "dead",
  jobtype: "Personal / Community / Full-stack Developer / Designer / System Administration",
  contract: "",
  type: "Community",
  tag: ["community", "emulation", "gameserver"],
  stack: ["java", "bash", "googlecode", "ipboard", "html", "css", "php", "xml"],
  gallery: [],
  video: [],
  live: null,
  source: "https://code.google.com/archive/p/aion-galaxy-emu/",
  lab: false,
  year: 2012,
}
