module.exports = {
  src: require("~/assets/portfolio/elegance.jpg"),
  title: "Elegance",
  subtitle: "HTML5 Theme / WordPress",
  desc: "Custom built commercial HTML5 theme with WordPress implementation.",
  role: "Slice a Photoshop .PSD based design into bootstrap HTML5/CSS3 theme with later based WordPress implementation. Project got rejected once due it\"s simplicity and later cancelled by developer.",
  status: "cancelled",
  stage: "dead",
  jobtype: "Commercial / Full-stack Developer / Designer",
  contract: "Envato",
  type: "Contract",
  tag: ["envato", "theme", "commercial"],
  stack: ["javascript", "html5", "bootstrap", "css3", "photoshop"],
  gallery: [
    require("~/assets/portfolio/elegance.jpg"),
    require("~/assets/portfolio/elegance/screen1.png"),
    require("~/assets/portfolio/elegance/screen2.png"),
    require("~/assets/portfolio/elegance/screen3.png"),
    require("~/assets/portfolio/elegance/screen4.png"),
  ],
  video: [],
  live: null,
  source: null,
  lab: null,
  year: 2014,
}
