module.exports = {
  src: require("~/assets/portfolio/elobg.jpg"),
  title: "ELO.BG",
  subtitle: "Electronic League Observations Lab Platform",
  desc: "ELO.bg is an eSports platform for analysing and coaching of players, creating and managing micro-communities and much more.",
  role: "Creating the model & developing the entire platform & design base, leading operations. Created several prototypes soon to be open sourced using MeteorJS, NuxtJS, MongoDB, OctoberCMS (since 2013). Created simultaneous connections to the Riot API using micro-services, fetching data and updating summoner profiles. ",
  status: "progress",
  stage: "early-bird",
  jobtype: "Personal / Full-stack Developer / Designer",
  contract: null,
  type: "Web/Mobile Application",
  tag: ["esports", "community", "design", "development", "administration", "data", "analytics", "optimization"],
  stack: ["laravel", "vuejs", "mariadb", "nginx", "cloudflare", "webpack", "redis", "node", "php", "gitlab", "sass", "es6", "meteorjs", "varnish", "rest", "octobercms", "nuxtjs", "mongodb"],
  gallery: [],
  video: ["kaok9eCqnus", "fC_gvB7BYJY", "jPtNEOPjV1k", "a81cJddYrK8", "STctKor1JnQ", "NcxcmwDS_ak", "hUlyJVaQkBg", "mQhNxsZhQQQ", "Uigr7ssobT0", "ssC1Z1m-2yw", "ff_GBOlvfm0", "SZfT8b44OFk", "9AICCs66v30", "J7YfsDPtCWY", "fdiVLqowTKc", "WUIz4W-hFjk",],
  live: "https://elo.bg",
  source: null,
  lab: null,
  year: 2017,
};
