module.exports = {
  src: require("~/assets/portfolio/fpsbg.jpg"),
  title: "FPS Bulgaria",
  subtitle: "Game Servers",
  desc: "Created entire game servers network with automated systems and administration.",
  role: "One of my most ambitious projects. Created a management team, a network of game servers, custom design and implementation of a web system merging WHMCS and phpBB with custom design, ban systesms, payment integration, game servers management and monitoring, custom-built firewalls. My work was to do the technical part of the project, partially managing the teams, adding new features to the system and bug fixing. I worked with several programming and markup languages, did game server modifications, ran ad-campigns, created hundreds of designs / banners / logos. Started a sister-project for game servers network container.",
  status: "ended",
  stage: "dead",
  jobtype: "Personal / Full-stack Developer / Designer / System Administration",
  contract: "",
  type: "Personal",
  tag: ["gaming", "servers"],
  stack: ["javascript", "html5", "bootstrap", "css3", "photoshop", "phpbb", "wordpress", "php5", "hlstatsx", "pawn", "bash", "python", "mariadb", "apache", "nginx", "cplus"],
  gallery: [
    require("~/assets/portfolio/fpsbg.jpg"),
    require("~/assets/portfolio/fpsbg/1.jpg"),
    require("~/assets/portfolio/fpsbg/2.jpg"),
    require("~/assets/portfolio/fpsbg/3.jpg"),
  ],
  video: [],
  live: null,
  source: null,
  lab: null,
  year: 2014,
}
