module.exports = {
  src: require("~/assets/portfolio/freeuikitvincentloginform.jpg"),
  title: "Free UI Kit Vincent Login Form",
  subtitle: "UI Kit Experiment",
  desc: "Plain CSS/HTML login/register form experiment.",
  role: "Create the entire experiment by example",
  status: "done",
  stage: "finished",
  jobtype: "Personal / Full-stack Developer",
  contract: "",
  type: "Personal",
  tag: ["experiment"],
  stack: ["html5", "css3"],
  gallery: [],
  video: [],
  live: "https://tsvetowntopalov.github.io/free-ui-kit-vincent-login-form/",
  source: "https://github.com/tsvetowntopalov/tsvetowntopalov.github.io/tree/master/free-ui-kit-vincent-login-form",
  lab: true,
  year: 2017,
}
