module.exports = {
  src: require("~/assets/portfolio/fsbweather.jpg"),
  title: "FSBWeather",
  subtitle: "Fullscreen Weather Background WordPress Plugin",
  desc: "WordPress plugin designed in matters of functionality, usability and stylish design. With this plugin you can easily turn your static WordPress template into great looking multimedia web site. You can select between dozens of transparent patterns to cover your video background in order to fit every web site template.",
  role: "Code / Design & Maintenance of the plugin.",
  status: "finished",
  stage: "dead",
  jobtype: "Commercial /  Full-stack Developer / Designer",
  type: "WordPress Plugin",
  contract: "Envato",
  tag: ["wordpress", "plugin", "weather", "video"],
  stack: ["php", "html5", "javascript", "wordpress", "videojs"],
  gallery: [],
  video: [],
  live: null,
  source: "https://github.com/tsvetowntopalov/fsbweather-wordpress",
  lab: null,
  year: 2013,
};
