module.exports = {
  src: require("~/assets/portfolio/inspirationloginimbatman.jpg"),
  title: "Inspirational Fingerprint Login - Batman",
  subtitle: "UI Kit Experiment",
  desc: "Authored Plain JS/CSS/HTML Inspirational Fingerprint Login.",
  role: "Create the entire experiment by authored design",
  status: "done",
  stage: "finished",
  jobtype: "Personal / Full-stack Developer / Designer",
  contract: "",
  type: "Personal",
  tag: ["experiment"],
  stack: ["html5", "css3", "less", "javascript"],
  gallery: [],
  video: [],
  live: "https://tsvetowntopalov.github.io/inspiration-login-im-batman/",
  source: "https://github.com/tsvetowntopalov/tsvetowntopalov.github.io/tree/master/inspiration-login-im-batman",
  lab: true,
  year: 2017,
}
