module.exports = {
  src: require("~/assets/portfolio/lanservers.jpg"),
  title: "Lan-Servers / Ex. Herehost",
  subtitle: "VPS & Dedicated Hosting Platform",
  desc: "Design & implementation of custom theme & features in the WHMCS platform.",
  role: "Using the popular Arka theme for WordPress implement custom pages & features directly to the WHMCS. Created 20+ custom pages with custom modules, design implementations and functionalities. Complete working themed solution for WHMCS including Home, Domains, 2 Custom VPS pages, Dedicated servers custom order page, Colocation with fancy animated order form, several about us/contacts/tos and support pages. Styled every basic WHMCS component with the Arka style. Created simple array configuration for the basic user with multilanguage integration. Various SEO techinques.",
  status: "finished",
  stage: "completed",
  jobtype: "Contract / Full-stack Developer / Designer",
  contract: "Lan-Servers",
  type: "Front-end",
  tag: ["hosting", "vps", "dedicated"],
  stack: ["javascript", "html5", "wordpress", "mysql", "jquery", "bootstrap", "css3", "php", "whmcs", "laravel", "photoshop", "php7"],
  gallery: [
    require("~/assets/portfolio/lanservers/1.jpg"),
    require("~/assets/portfolio/lanservers/2.jpg"),
    require("~/assets/portfolio/lanservers/3.jpg"),
    require("~/assets/portfolio/lanservers/4.jpg"),
    require("~/assets/portfolio/lanservers/5.jpg"),
    require("~/assets/portfolio/lanservers/6.jpg"),
  ],
  video: [],
  live: "https://lan-servers.com",
  source: null,
  lab: null,
  year: 2017,
};
