module.exports = {
  src: require("~/assets/portfolio/micropanel.jpg"),
  title: "Micropanel",
  subtitle: "MicroPanel Admin Theme plugin for WordPress",
  desc: "Micropanel is clean and unique WP Admin Template. With simple installation and user-friendly interface it distracts your from the boring default administration presented by WordPress.",
  role: "Creating custom WordPress admin theme plugin with options. Coding Nik Pletikos\" design in HTML5/CSS3.",
  status: "finished",
  stage: "dead",
  jobtype: "Commercial /  Full-stack Developer / Designer",
  contract: "Envato",
  type: "WordPress Plugin",
  tag: ["admin", "theme", "wordpress"],
  stack: ["javascript", "php", "wordpress", "wpapi", "css3"],
  gallery: [
    require("~/assets/portfolio/micropanel/elepanel_index.jpg"),
    require("~/assets/portfolio/micropanel/elepanel_login.jpg"),
    require("~/assets/portfolio/micropanel/elepanel_post_exp.jpg"),
    require("~/assets/portfolio/micropanel/elepanel_post_hover.jpg"),
    require("~/assets/portfolio/micropanel/elepanel_post_normal.jpg"),
    require("~/assets/portfolio/micropanel/new_post_text.jpg"),
    require("~/assets/portfolio/micropanel/new_post_visual.jpg"),
    require("~/assets/portfolio/micropanel/widget.jpg"),
  ],
  video: [],
  live: null,
  source: "https://github.com/tsvetowntopalov/micropanel-wordpress",
  lab: null,
  year: 2013,
};
