module.exports = {
  src: require("~/assets/portfolio/myghost.jpg"),
  title: "MyGhost.host",
  subtitle: "Ghost Hosting Platform",
  desc: "Fully featured platform for hosting Ghost blogs and selling Ghost themes.",
  role: "Developing of the entire SaaS platform. Integrating payment functions using Paypal & Stripe with custom subscription system. Using LXDs on top of Google Cloud and LXC API to manage the containers with custom images and Ghost installation inside a multitenant database. Creating system to manage those containers, set up new blogs, manage blogs, manage themes and more.",
  status: "progress",
  stage: "early-bird",
  jobtype: "Personal / Full-stack Developer / Designer / System Administration",
  contract: "",
  type: "Personal",
  tag: ["hosting"],
  stack: ["javascript", "html5", "css3", "photoshop", "laravel", "percona", "php7", "vuejs", "ssr", "ghost", "lxd", "lxc", "google-cloud"],
  gallery: [],
  video: [],
  live: 'https://myghost.host',
  source: null,
  lab: null,
  year: 2014,
};
