module.exports = {
  src: require("~/assets/portfolio/reminderconcept.jpg"),
  title: "Reminder Concept",
  subtitle: "UI Experiment for Reminder App",
  desc: "Plain CSS/HTML/JS UI Experiment for Reminder App.",
  role: "Create the entire experiment by inspirational design @ Dribble",
  status: "done",
  stage: "finished",
  jobtype: "Personal / Full-stack Developer",
  contract: "",
  type: "Personal",
  tag: ["experiment"],
  stack: ["html5", "css3", "javascript"],
  gallery: [],
  video: [],
  live: "https://tsvetowntopalov.github.io/reminder-concept/",
  source: "https://github.com/tsvetowntopalov/tsvetowntopalov.github.io/tree/master/reminder-concept",
  lab: true,
  year: 2017,
}
