module.exports = {
  src: require("~/assets/portfolio/snowfall.jpg"),
  title: "Snowfall Background",
  subtitle: "Background Experiment",
  desc: "Plain CSS/HTML/JS Background Experiment.",
  role: "Create the entire experiment by inspiration",
  status: "done",
  stage: "finished",
  jobtype: "Personal / Full-stack Developer",
  contract: "",
  type: "Personal",
  tag: ["experiment"],
  stack: ["html5", "css3", "javascript"],
  gallery: [],
  video: [],
  live: "https://tsvetowntopalov.github.io/snowfall/",
  source: "https://github.com/tsvetowntopalov/tsvetowntopalov.github.io/tree/master/snowfall",
  lab: true,
  year: 2017,
}
