module.exports = {
  src: require("~/assets/portfolio/sumenu.jpg"),
  title: "Sumenu",
  subtitle: "Bootstrap Super Menu Navigation",
  desc: "Complete menu set for your web site. Perfect for any color and any resolution. It is responsive and fits perfect with multi-color scheme",
  role: "Create and design complete Bootstrap navigation set.",
  status: "finished",
  stage: "dead",
  jobtype: "Commercial / Full-stack Developer / Designer",
  contract: "Envato",
  type: "HTML5 Plugin",
  tag: ["navigation", "bootstrap"],
  stack: ["javascript", "html5", "jquery", "bootstrap", "css3"],
  gallery: [],
  video: [],
  live: null,
  source: "https://github.com/tsvetowntopalov/",
  lab: null,
  year: 2012,
};
