module.exports = {
  src: require("~/assets/portfolio/vskexpres.jpg"),
  title: "VSK Express",
  subtitle: "Banking Organisation Management Platform",
  desc: "Management platform for banking-type organisation. Used to manage users, loans, billing, and more.",
  role: "Create and design complete set of features and build from ground up the entire platform. Several reworks using latest frameworks until patching things up to laravel5. Design and integration of custom modules. Integration with Excel, CVS & PDF documents. Graphs and logs for users balance, loans and more. Sole purpose for the project was automatition of calculations and easier tracking and management of users, migrating from earlier Microsoft\"s Excel tables format. The system is set to scale to full-blown multi-tenant SaaS platform, allowing multiple banking institutions to manage their users, payments and loans.",
  status: "progress",
  stage: "early-bird",
  jobtype: "Contract / Full-stack Developer / Designer",
  contract: "ВСК Експрес",
  type: "Web App",
  tag: ["finance", "cms"],
  stack: ["javascript", "html5", "mariadb", "mysql", "jquery", "bootstrap", "css3", "php", "php7", "laravel", "simple-php", "photoshop", "nginx", "cloudflare", "vuejs"],
  gallery: [],
  video: ["U1EeDMd8MTM"],
  live: "https://vskexpres.bg",
  source: null,
  lab: null,
  year: 2013,
};
