module.exports = {
  src: require("~/assets/portfolio/witchergiveaway.jpg"),
  title: "The Witcher 3 DLC Animation",
  subtitle: "Witcher Giveaway Animation Experiment",
  desc: "Plain CSS/HTML/JS Giveaway landing page experiment.",
  role: "Create the entire experiment by design @ dribble",
  status: "done",
  stage: "finished",
  jobtype: "Personal / Full-stack Developer",
  contract: "",
  type: "Personal",
  tag: ["experiment"],
  stack: ["html5", "css3", "javascript", "jquery", "webpack", "babel", "sass", "es6", "photoshop"],
  gallery: [],
  video: [],
  live: "https://tsvetowntopalov.github.io/witcher-giveaway/",
  source: "https://github.com/tsvetowntopalov/tsvetowntopalov.github.io/tree/master/witcher-giveaway",
  lab: true,
  year: 2017,
}
